"""Initial migration with all models

Revision ID: fd191c05ba31
Revises: 
Create Date: 2025-11-26 13:26:34.685665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd191c05ba31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('call_count', sa.Integer(), nullable=False),
    sa.Column('last_reset', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_usage_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_usage_log_date'), ['date'], unique=True)

    op.create_table('ticker_pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('market_cap', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'exchange', name='unique_ticker_exchange')
    )
    with op.batch_alter_table('ticker_pool', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticker_pool_exchange'), ['exchange'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticker_pool_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticker_pool_sector'), ['sector'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticker_pool_ticker'), ['ticker'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticker_pool_timezone'), ['timezone'], unique=False)

    op.create_table('ticker_prices',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('traders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'ARCHIVED', name='traderstatus'), nullable=False),
    sa.Column('initial_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('strategy_name', sa.String(length=50), nullable=False),
    sa.Column('risk_tolerance', sa.String(length=20), nullable=False),
    sa.Column('trading_ethos', sa.Text(), nullable=True),
    sa.Column('trading_timezone', sa.String(length=50), nullable=False),
    sa.Column('custom_watchlist', sa.JSON(), nullable=True),
    sa.Column('watchlist_size', sa.Integer(), nullable=False),
    sa.Column('use_custom_watchlist', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_trade_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trader_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('average_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('first_purchased_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trader_id', 'ticker', name='unique_trader_ticker')
    )
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_ticker'), ['ticker'], unique=False)

    op.create_table('ticker_rotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('trader_id', sa.Integer(), nullable=True),
    sa.Column('last_analyzed_at', sa.DateTime(), nullable=False),
    sa.Column('analysis_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'timezone', 'trader_id', name='unique_ticker_timezone_trader')
    )
    with op.batch_alter_table('ticker_rotation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticker_rotation_last_analyzed_at'), ['last_analyzed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticker_rotation_ticker'), ['ticker'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticker_rotation_timezone'), ['timezone'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticker_rotation_trader_id'), ['trader_id'], unique=False)

    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trader_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('action', sa.Enum('BUY', 'SELL', name='tradeaction'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rsi', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('macd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sma_20', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sma_50', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('recommendation', sa.String(length=10), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trades_executed_at'), ['executed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_ticker'), ['ticker'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trades_ticker'))
        batch_op.drop_index(batch_op.f('ix_trades_executed_at'))

    op.drop_table('trades')
    with op.batch_alter_table('ticker_rotation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticker_rotation_trader_id'))
        batch_op.drop_index(batch_op.f('ix_ticker_rotation_timezone'))
        batch_op.drop_index(batch_op.f('ix_ticker_rotation_ticker'))
        batch_op.drop_index(batch_op.f('ix_ticker_rotation_last_analyzed_at'))

    op.drop_table('ticker_rotation')
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_ticker'))

    op.drop_table('portfolio')
    op.drop_table('traders')
    op.drop_table('ticker_prices')
    with op.batch_alter_table('ticker_pool', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticker_pool_timezone'))
        batch_op.drop_index(batch_op.f('ix_ticker_pool_ticker'))
        batch_op.drop_index(batch_op.f('ix_ticker_pool_sector'))
        batch_op.drop_index(batch_op.f('ix_ticker_pool_is_active'))
        batch_op.drop_index(batch_op.f('ix_ticker_pool_exchange'))

    op.drop_table('ticker_pool')
    with op.batch_alter_table('api_usage_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_usage_log_date'))

    op.drop_table('api_usage_log')
    # ### end Alembic commands ###
